services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: fastapi-backend:latest
    container_name: fastapi-container
    env_file:
      - .env
    ports:
      - "8000:10000"  # map host port 8000 to container port 10000 (matches Dockerfile's EXPOSE & CMD)
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:10000/ping || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s
